### ISSUE TITLE
Move events handling to the Update tree

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#100]
This is a reminder issue.

Right now `widget.Widget` handles the events inside the `Render` method which is a part of `ebiten.Game.Draw` tree.

This works OK for desktop platforms (to my knowledge), but it fails short for mobile platforms due to the touch position reset in-between the Update calls. While this touch-related issue can be fixed separately with a cludge, it would be better if we could move the logic-related code to the `Update` tree.

This issue should not be closed with a mobile touch-related fix. It should remain open until the real underlying problem is fixed.

**Comment by mcarpenter622** [comment]
This is a smart idea, and I will make this the next big change I do. It will be a large change and honestly I am really unsure why it wasn't built this way to begin with.

**Comment by quasilyte** [comment]
For now, the users can adopt this pattern if running handler logic should happen inside Update tree:
```go
// The handler is called inside Draw() tree.
// Instead of running the action itself, we append it to slice.
ButtonOpts.ClickedHandler(func(args *widget.ButtonClickedEventArgs) {
    ctx.deferredEvents = append(ctx.deferredEvents, func() {
        onClickAction()
    })
})

// Somewhere inside the Update tree:
for _, f := range ctx.deferredEvents {
    f()
}
ctx.deferredEvents = ctx.deferredEvents[:0]
```

It's not perfect, but it works.

**Comment by mcarpenter622** [comment]
This is done!

**Comment by quasilyte** [comment]
I need to grab this update right meow. :D
