### ISSUE TITLE
Tabbook should have a distinct hovered and activated states

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#102]
Otherwise, it's hard to distinguish a hovered-on tab and currently activated tab:

![image](https://github.com/ebitenui/ebitenui/assets/6286655/5619562b-db68-4829-9914-0d2eefbf72eb)

Note that using "tab" or any keyboard-based navigation makes it even more confusing as it does focus the next tab, but does not activate it: we end up with 2 tab buttons looking identically.

**Comment by mcarpenter622** [comment]
Hey @quasilyte I know this is old. I hope you were able to figure this one out. Button has a separate image for hover than pressed:

	Idle         *image.NineSlice
	Hover        *image.NineSlice
	Pressed      *image.NineSlice
	PressedHover *image.NineSlice
	Disabled     *image.NineSlice

**Comment by quasilyte** [comment]
Hmm. Perhaps I was confused by the way Demo example worked.

**Comment by mcarpenter622** [comment]
I'm closing this for now. Please reach out if you need anything further for this one.
