### ISSUE TITLE
Friendlier messages when widget options are missing

### ISSUE THREAD

**Issue by williammoran** [mcarpenter622/ebitenui#109]
With the current design, it's often not clear which options are required and which are optional. Unfortunately, if a required one is omitted, it results in an unhelpful nil pointer dereference.
It would make the library easier to use if option processing validated that all required options were present, and provided a specific error when they're missing. Something like, "List widget is missing required WidgetOps option"

**Comment by mcarpenter622** [comment]
I agree. I'll look into it

**Comment by mcarpenter622** [comment]
This has been added with this commit:
https://github.com/ebitenui/ebitenui/commit/d5405bee081a9863a7ad91b4d27542ce8e69a1f5

Thank you!
