### ISSUE TITLE
Outdated text API

### ISSUE THREAD

**Issue by setanarut** [mcarpenter622/ebitenui#148]
Ebitenui needs to be updated according to Ebitengine text v2 api.
https://ebitengine.org/en/documents/2.7.html#New_Text_Rendering_Package_text/v2

**Comment by mcarpenter622** [comment]
Updated in the latest commit. I will cut a new release with it soon, but want to give people a chance to play with it first
https://github.com/ebitenui/ebitenui/commit/bac907fba2ce701770a0ed47233ee516868d8011
