### ISSUE TITLE
How the `TextInput` widgget surpports multiple lines?

### ISSUE THREAD

**Issue by zrcoder** [mcarpenter622/ebitenui#16]
and how to show line numbers?

**Comment by blizzy78** [comment]
`TextInput` does not currently support multiline input or line numbers.

**Comment by mcarpenter622** [comment]
@zrcoder I know this is 18 months old or so but I just recently took over. One of the first changes I made was to add a TextArea widget with linewrap and scrolling.  It doesn't do line numbers automatically, but it will support multiple lines now. I would love if you'd take another look at the lib sometime!

**Comment by airtonix** [comment]
> @zrcoder I know this is 18 months old or so but I just recently took over. One of the first changes I made was to add a TextArea widget with linewrap and scrolling. It doesn't do line numbers automatically, but it will support multiple lines now. I would love if you'd take another look at the lib sometime!

mind linking to where you did this?

**Comment by mcarpenter622** [comment]
You can see an example here:
https://ebitenui.github.io/textarea/
 And here
https://ebitenui.github.io/
Select TextArea on the left .
Currently it doesn't allow direct input but that is an open ticket.
