### ISSUE TITLE
Allow to trigger 'Pressed' events

### ISSUE THREAD

**Issue by xescugc** [mcarpenter622/ebitenui#169]
In my current game I have keybinds in order to click some stuff, you have the option to manually click it or to use the keybinds.

The issue is that using `button.Click()` does not have the same visual effect as clicking manually.

Manually clicking has the pressing effect that you can just keep the left button pressed and it would be visible and count as 1 click. With the current API I think this is not possible except if you send `Click()` all the time but that is obviously not a solution.

**Comment by mcarpenter622** [comment]
So, I don't think I fully understand the request. The Click() does allow you to trigger the event which will fire ClickedEvent and StateChangedEvent. Are you requesting that it fire PressedEvent and ReleasedEvent as well?  

OR is this a visual thing? Like if someone calls the Click() method you'd like it to show it pressed for x number of frames before firing released/clicked?

**Comment by xescugc** [comment]
Yes it's more on the visual side.

If you click you normally are pressing for longer that 1 TPS (except if you are REALLY fast haha). So I was looking for a way to basically do the same but instead of using the mouse to click the buttion, use a keybind to "click" it.

The logic itself RN is that when the user presses the key i `.Click` the button but visually it's basically not visible as it's only visible for 1TPS and the act of holding it down is not "visible" as if you where to keep the left mouse pressed.
