### ISSUE TITLE
Button Graphic with more options

### ISSUE THREAD

**Issue by xescugc** [mcarpenter622/ebitenui#205]
I'm using now the `widget.ButtonOpts.Graphic(img)` which allows to set an image to the BTN without using Stacked.

I would like to have the same logic I did on https://github.com/ebitenui/ebitenui/pull/184 but also adding `Pressed`.

So which is the best route? I was thinking on adding a new `widget.ButtonOpts.GraphicImages(imgs)` that would basically use the same API I did for the other PR. That is easy, the issues is when trying to do the `Pressed` as the `Widget` has no knowledge of it, should we also add a `Widget.Pressed` same way we have `Widget.Disabled`?

If not the other way is to copy part of the logic on `TextAndImage` that has:

```
type ButtonImageImage struct {
	Idle     *ebiten.Image
	Disabled *ebiten.Image
}
```

We could add the `Pressed` and on `Render` extend the logic already existent to use either `Idle` or `Disabled` to check the `b.pressed` (and the other check done on other methods) to change the image of the `Graphic` to the one we want.

WDYT is the one you prefer?

**Comment by mcarpenter622** [comment]
So to be honest, I've always hated how it handles Button graphics. My preference is to expose GraphicImage as an option on Button and add the Pressed *ebiten.Image and Hover *ebiten.Image to that struct then modify Button's Render method to utilize it.
