### ISSUE TITLE
Textbox doesn't recognize Numpad enter as enter for submit, and this feature should be optional all along.

### ISSUE THREAD

**Issue by YindSoft** [mcarpenter622/ebitenui#207]
Right now when you press Enter you can submit the textbox, but it only works with the main Enter it doesn't with Numpad Enter.

Also, this is nice to have it out of the box but there should be a config for allowing enter to submit the textbox.

**Comment by YindSoft** [comment]
https://github.com/ebitenui/ebitenui/pull/208

PR for this fix and feature

**Comment by mcarpenter622** [comment]
PR merged
