### ISSUE TITLE
Components retain IsFocused() true when they are not visible.

### ISSUE THREAD

**Issue by YindSoft** [mcarpenter622/ebitenui#209]
If I have a component that is focus and set it to Visibility_hide, it will retain focus which shouldn't be the behaviour.

Right now we access the direct variable for setting visibility, but it would be better to have a method so when it's set to invisible it should send focus to the next component.

Probably something similar happens when disabled.

**Comment by mcarpenter622** [comment]
Just merged your PR for this. Thank you
