### ISSUE TITLE
Can no longer call ui.Update() in 0.6.0 even though the examples use it 

### ISSUE THREAD

**Issue by AJLProjects** [mcarpenter622/ebitenui#230]
I am on version  0.6.0 but the ui.Update function has become private, and lowercase'd. So I can no longer access this. 
There is no guidance on this.
Shouldn't the version 0.6.0 have an 'Update' function on the type: ebitenui.UI

**Comment by mcarpenter622** [comment]
I think there is something else going on here.  Update() is still there. See the link below. Do you perhaps have an aliasing problem where there is a different variable or import called ui?

  https://github.com/ebitenui/ebitenui/blob/831a4e82b1d374b9d35361c7da2b8b8fe8e7a242/ui.go#L40

**Comment by AJLProjects** [comment]
![image](https://github.com/user-attachments/assets/5198c21e-fdea-4804-b74d-37ffd49f1a29)
This is very weird. Maybe an issue with my package loader?

**Comment by AJLProjects** [comment]
It was the package system not your fault. 
When it was doing a checksummy thing it didn't spot the difference in case.

**Comment by AJLProjects** [comment]
I just deleted the package and redownloaded.

**Comment by mcarpenter622** [comment]
That is very strange. At no point was that method not exported. I don't know how that could even show up like that.
