### ISSUE TITLE
Add arrows switch widget focus to the example

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#34]
If that's possible, it would be good to add this as a separate example (it could be an addition to "demo" example, but it's so big already, very overwhelming).

Most real-life UIs should have a way to handle input focus switching. Otherwise, we're making the player rely solely on the mouse (which is inconvenient if the game can be played without the mouse at all).

This is mostly useful in menus with simple layout like this:
```
[ button1 ] // <- focused by default
[ button2 ]
[ button3 ]
```

**Comment by mcarpenter622** [comment]
That is a great suggestion and something I've been considering quite a bit. 
I am thinking this is actually 2 separate changes.
1) Tab to move between controls.  [button1] -> [combo box] -> [button 2]
2) Arrows to move between options in a single widget combo box: [option 1] -> [option 2]

Also, I agree with you about the demo example being ridiculous! I am starting to break them down to individual demos per ui widget. This is one of the first ones I've done -> https://github.com/ebitenui/ebitenui/tree/master/_examples/widget_demos/button

**Comment by quasilyte** [comment]
As a side note, that button example you referenced was quite useful to help me get started!

**Comment by mcarpenter622** [comment]
@quasilyte Just a heads up. This is now available in v.0.3.0. I am going to close this ticket. Please check it out and let me know what you think!
