### ISSUE TITLE
Consider adding a comment for the root container  of demo example

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#47]
https://github.com/ebitenui/ebitenui/blob/24d44f428ccc5e1bd899a6adbc23df2966d13fca/_examples/demo/main.go#L63-L72

It's not very clear for the unexperienced user why a single-column grid layout is used instead of a row layout.
If there is a reason for that, it should probably be stated in the comment.
From a user point of view, a single column grid shouldn't be very different from the row layout.

**Comment by mcarpenter622** [comment]
Done
