### ISSUE TITLE
A disabled text input can still be focused, the cursor is blinking

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#48]
![image](https://user-images.githubusercontent.com/6286655/222956033-fed1df54-67fe-4047-904b-1152cd499a55.png)

I think this behavior can confuse users if disabled input images are not obvious enough.
The user would think that there is a problem with their keyboard (or other input method).

I would assume that disabled element can't receive focus; or at least the text cursor shouldn't show up (neither blink).

**Comment by mcarpenter622** [comment]
This should be fixed now
