### ISSUE TITLE
Add online demo to the docs GitHub pages

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#52]
GitHub pages on https://ebitenui.github.io/ could have an online demo.
With #50 it should be possible to build `_examples/demo` for wasm.

```bash
cd _examples/demo
GOOS=js GOARCH=wasm go build -o main.wasm .
```

An example of this is https://quasilyte.dev/ebitenui/
(https://github.com/quasilyte/quasilyte.github.io/tree/master/ebitenui)

It could be embedded in the page in such a way that it looks more appropriate for the docs site.

**Comment by mcarpenter622** [comment]
Woo hoo I got it working: 
https://ebitenui.github.io/

I think I will keep this one open because I want to try a few other things:
1) Build the wasm in the github actions for each of the examples and the demo and commit them back into the project.
2)  Link to those versions of the wasm if I can.

**Comment by mcarpenter622** [comment]
Ok so I have been able to get 1 and 2 working now! I will go ahead and close this particular request. Please reach out or create a new ticket if you have any additional questions / thoughts
