### ISSUE TITLE
Tooltip display when it doesn't fit the screen

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#53]
![image](https://user-images.githubusercontent.com/6286655/222979188-f5e934e2-838a-490c-870b-958e4a770841.png)

If there is not enough space in the right part of the screen, the tooltip should probably position itself to the left, so it fits the screen.

If UI elements are positioned to the right side of the screen, it would be impossible to read a tooltip if it tries to render itself to the right side as well.

**Comment by mcarpenter622** [comment]
That is a good suggestion and this will get added to the backlog. In the meantime for anyone seeing this issue, you can manually set the anchor points for the tooltip to help with visibility
