### ISSUE TITLE
Exception trying to set labeled checkbox state just after creation

### ISSUE THREAD

**Issue by harbdog** [mcarpenter622/ebitenui#56]
Using ebitenui v0.4.0, I'm creating some labeled checkboxes and sometimes they need to be checked on by default. However, the .Checkbox() function returns nil after initial creation, which is needed to access its .SetState() function. It appears the checkbox object underneath doesn't get set until after the .init.Do() function is called, which is only performed after first calling one of a few functions which aren't always necessary to do up front (GetWidget, PreferredSize, SetLocation, SetupInputLayer, Render, Focus).

At the least I think it would be worth adding a SetState() function directly on the labeled checkbox object which can call the .init.Do() first to ensure it will be present.

**Comment by harbdog** [comment]
The current workaround looks something like this:

```golang
c := widget.NewLabeledCheckbox...

if checked {
    c.GetWidget()
    c.Checkbox().SetState(widget.WidgetChecked)
}
```

**Comment by mcarpenter622** [comment]
Thank you for the PR
