### ISSUE TITLE
Labeled Checkbox inside moveable window does not move with it

### ISSUE THREAD

**Issue by harbdog** [mcarpenter622/ebitenui#58]
When a labeled checkbox is added to a moveable window, it does not move with it, instead staying in the same place it was where the window was first opened.

Example code: https://github.com/ebitenui/ebitenui/compare/v0.4.1...harbdog:ebitenui:window_checkbox_issue

**Comment by harbdog** [comment]
When a checkbox is added to a moveable window, it does not move with it, instead staying in the same place it was where the window was first opened.

Example code: https://github.com/ebitenui/ebitenui/compare/v0.4.1...harbdog:ebitenui:window_checkbox_issue

**Comment by harbdog** [comment]
![recording](https://user-images.githubusercontent.com/1300522/224520774-7b0fac53-ce76-47ed-a4a1-907df4e6c937.gif)

**Comment by mcarpenter622** [comment]
Can you please confirm the version of the library you're using? This should be fixed on the v.0.4.0 release.

**Comment by harbdog** [comment]
I just updated to v0.4.1 to pick up the labeled checkbox updates

**Comment by mcarpenter622** [comment]
Interesting, I'll let you know I just fixed a similar issue with the plain checkbox. I should be able to get a resolution later tonight.

**Comment by mcarpenter622** [comment]
To get you through until I can do some additional testing I made a small fix to the labeledCheckbox. I think its a bandaid, so I will not cut a proper release until I can investigate it further. Until then you can pull the latest commit: 

`go get github.com/ebitenui/ebitenui@a1aa777
`

The root issue is that the container was not telling its children to update their position when it moved. I added the line to do that, but I'm sure there is a cleaner fix that will work better long term

**Comment by harbdog** [comment]
confirming that commit works though I can wait until the next release/patch for it

**Comment by mcarpenter622** [comment]
So I've released a couple versions that should fix this issue. Take a look and let me know. If I don't hear anything I'll plan to close this issue in a few days
