### ISSUE TITLE
Improve the grid-like container navigation

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#61]
For now, we have focus change directions of next/previous.
This is good enough for horizontal or vertical layouts like these:
```
vertical: next is right, prev is left
[x][x][x][x]

horizontal: next is down, prev is up
[x]
[x]
[x]
[x]
```
It becomes less intuitive with grid-like layouts (inventory, achievements grid, etc.):
```
grid layout: can only traverse it in a linear one after another way, from the upper left to the bottom right
[x][x][x]
[x][x][x]
[x][x][x]
```

I propose that we add an alternative focus-changing scheme with directions (4 of them).
For the already existing vertical and horizontal behaviors the change is trivial:

* horizontal layout: prev=left, next=right, up and down=nothing
* vertical layout: prev=up, next=down, left and right=nothing

For the grid layout we can now have a better navigation system.

It could be possible to implement this in the user-land, but it will be messy, since we'll have to take the layout into account while doing the computations.

Without this feature, any keyboard/gamepad based navigation over the grid becomes clumsy and inconvenient. In turn, it forces the game developers that are using this library to avoid any grid setups to mitigate the limitations.

My personal opinion is that directional buttons should not go out of the layout easily. When you press left on the horizontal layout while focusing the leftmost element, it should wrap around and select the rightmost element, not some other random widget that happened to be somewhere. We need a separate action for that like "select next group" which could be assigned to tab or whatever. If layout-based solution is not good enough here, groups can be (and maybe they **should** be) marked by the user explicitly.

**Comment by mcarpenter622** [comment]
Because of how complex focus navigation can be to try to automatically figure out, I've added the ability specify focus directions manually by the user. This will allow you to determine exactly how you want your focus directions to work.  See this new example: 
https://github.com/ebitenui/ebitenui/blob/master/_examples/widget_demos/manual_focus/main.go

I am going to close this one for now.
