### ISSUE TITLE
CursorUpdater: how to set back to default?

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#64]
Doing `input.SetCursorUpdater(nil)` makes the game panic.
`internalinput.InputHandler` is internal.
There should be a way to redo the set operation.
Perhaps `SetCursorUpdater` should check for nil and set the updater back to the default state if it is, in fact, nil?
Since `SetCursorUpdater` will not be called in a loop, this extra check is ~free for us in terms of performance.

This is useful in games that don't use ebitenui in _all_ of their scenes. Or if they have different parts of the game, some of them may benefit from system defaults (like no ebitenui cursor skins are used).

**Comment by mcarpenter622** [comment]
This should be done now. I'll give it a couple days and close this ticket if I do not hear back.
