### ISSUE TITLE
CursorUpdater: a cursor disappears with nil replacement images

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#65]
Right now `CursorUpdater` can't be used for virtual cursors that co-exist with normal cursor.

In my game, there is a separate cursor for the gamepad that doesn't remove a normal mouse pointer.
Its sprite is controlled outside of the ebitenui; I move it according to the player's inputs.

The game knows when either of them is active. So it would make more sense to me to make a logic-only cursor updater: I want ebitenui to know the cursor coordinates and whether some buttons were pressed, but the image-related APIs are redundant in this case.

It can be solved in at least two ways:
1. There can be two interfaces. The current (full) interface and headless (new) interface for logic-only.
2. The current interface may handle nil images as "use the defaults" sign

This is probably the minimal interface that would work for me:
```go
type CursorUpdater interface {
	MouseButtonPressed(b ebiten.MouseButton) bool
	MouseButtonJustPressed(b ebiten.MouseButton) bool
	CursorPosition() (int, int)
	GetCursorOffset(name string) image.Point
}
```
This is a bridge from the game own logic to how ebitenui should handle cursor-related info.

**Comment by mcarpenter622** [comment]
I originally had the interface split like you suggest but changed it to
this because I have no way of setting the current system cursor location.
Ebiten doesnt have that capability. Because of this I cannot keep the
system cursor and an alternate cursor location in sync. That's why I made
it required to have custom cursor images if you use the setcursorupdater
option. I could possibly look into the libraries ebiten is using to do that
but I was hoping to avoid doing that.

**Comment by quasilyte** [comment]
Hmm, but in my case I don't need to move the original cursor when the gamepad cursor (a different entity) is moving. Some players may still want to use a mouse when changing the game options, etc. It's just nice to have an option to play without a mouse (with gamepad only), but some mixed situations are possible: both gamepad and mouse can be connected. It would be weird to move a system pointer by a gamepad and vice-versa, at least from my point of view.

If you know that `(x, y)` is supposed to have an active cursor as reported by a CursorUpdater, that should be enough to consider it's there. What I want to do is basically just let ebitenui know where the cursor is supposed to be at a given moment and whether some buttons are being pressed.

**Comment by mcarpenter622** [comment]
I'm not sure I understand your use case.

It seems a lot like the example cursorupdater which has the cursor
controlled by both the mouse and the keyboard?

Can you please describe your use case for me so that we're on the same page?

**Comment by quasilyte** [comment]
I sent a description of the case in Discord.
But at the very minimum, there should be a way to recover the default cursor.

I'm not using ebitenui in some of the scenes and they'll need to have a cursor visible.

**Comment by mcarpenter622** [comment]
I *believe* the changes I made resolve this issue. See latest commits. I will probably close this in the next couple days unless I hear back.
