### ISSUE TITLE
TextInput rendering two characters per keystroke

### ISSUE THREAD

**Issue by nmorenor** [mcarpenter622/ebitenui#68]
Hey I'm having an issue with text inputs where they get two characters printed per key stroke, this is also reproducible on the _examples/demo did some debugging and modifying the textinput.go

```
func (t *TextInput) doInsert(c []rune) {
	s := string(insertChars([]rune(t.InputText), c, t.cursorPosition))
	time.Sleep(50 * time.Millisecond)
	if t.validationFunc != nil {
		result, replacement := t.validationFunc(s)
		if !result {
			if replacement != nil {
				s = *replacement
			} else {
				return
			}
		}
	}

	t.InputText = s
	t.cursorPosition += len(c)
}
```

Seems to fix this, although this does not feel like the real fix.

**Comment by mcarpenter622** [comment]
This should be resolved now. Please let me know if you see any other issues!

https://github.com/ebitenui/ebitenui/releases/tag/v0.5.2
