### ISSUE TITLE
Text centering issues with bitmapfont

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#69]
1. Modify the button widget example as follows:

```diff
--- a/_examples/widget_demos/button/main.go
+++ b/_examples/widget_demos/button/main.go
@@ -7,10 +7,8 @@ import (
        "github.com/ebitenui/ebitenui"
        "github.com/ebitenui/ebitenui/image"
        "github.com/ebitenui/ebitenui/widget"
-       "github.com/golang/freetype/truetype"
+       "github.com/hajimehoshi/bitmapfont/v2"
        "github.com/hajimehoshi/ebiten/v2"
-       "golang.org/x/image/font"
-       "golang.org/x/image/font/gofont/goregular"
 )
 
 // Game object used by ebiten
@@ -22,8 +20,7 @@ func main() {
        // load images for button states: idle, hover, and pressed
        buttonImage, _ := loadButtonImage()
 
-       // load button text font
-       face, _ := loadFont(20)
+       face := bitmapfont.Face
 
        // construct a new container that serves as the root of the UI hierarchy
        rootContainer := widget.NewContainer(
@@ -49,7 +46,7 @@ func main() {
                widget.ButtonOpts.Image(buttonImage),
 
                // specify the button's text, the font face, and the color
-               widget.ButtonOpts.Text("Hello, World!", face, &widget.ButtonTextColor{
+               widget.ButtonOpts.Text("000\n111\n222", face, &widget.ButtonTextColor{
                        Idle: color.NRGBA{0xdf, 0xf4, 0xff, 0xff},
                }),
 
@@ -121,16 +118,3 @@ func loadButtonImage() (*widget.ButtonImage, error) {
                Pressed: pressed,
        }, nil
 }
-
-func loadFont(size float64) (font.Face, error) {
-       ttfFont, err := truetype.Parse(goregular.TTF)
-       if err != nil {
-               return nil, err
-       }
-
-       return truetype.NewFace(ttfFont, &truetype.Options{
-               Size:    size,
-               DPI:     72,
-               Hinting: font.HintingFull,
-       }), nil
-}
```

Basically, replace `loadFont()` with a direct use of [bitmapfont.Face](https://github.com/hajimehoshi/bitmapfont).

2. Run the example.

![image](https://github.com/ebitenui/ebitenui/assets/6286655/4c9e58f5-1b48-4e62-be1a-b63dee1d9b08)

The result is off-center text. This happens with any kind of text with this font.
The font is monospaced.

It could be a bitmapfont issue or ebitenui font handling issue.
It's more likely to be a bitmapfont issue, but it's hard to debug it outside of the context.
For instance, maybe it handles glyph advance incorrectly, providing a spacing for 1 extra trailing character?
Or maybe ebitenui doesn't handle this corner case correctly with different `font.Face` implementations?

The underlying `font.Face` implementation can be found here: https://github.com/hajimehoshi/bitmapfont/blob/main/internal/bitmap/bitmap.go

I'll link this issue to the bitmapfont repository issue as well.

**Comment by hajimehoshi** [comment]
Isn't `\n` rendered unexpectedly?

**Comment by quasilyte** [comment]
The issue persists even without a newline.
![image](https://github.com/ebitenui/ebitenui/assets/6286655/440f73d0-280f-4198-a3e9-d7a0b9aa6521)
I can also confirm that this issue can be reproduced by other widgets tool, like `widget.Text`:
![image](https://github.com/ebitenui/ebitenui/assets/6286655/1a663858-bd90-4f16-b5ef-30ff1b80e4b7)
The text is supposed to center-aligned inside a window, but it's not.

I would assume that this is a relevant piece of code:
https://github.com/ebitenui/ebitenui/blob/507f5ce2ede7819530d212ba20cdfbb2b846d7a5/widget/text.go#L267-L341

The line width is calculated as 378 for both bitmap font and the font used in the example, but they're still aligned differently:
![image](https://github.com/ebitenui/ebitenui/assets/6286655/25dc0f9e-0a0b-48eb-8d23-20c95de2d1df)

Ultimately, both fonts/texts end up here, with `lx=11`:
```go
text.Draw(screen, strings.Join(line, " "), t.Face, lx, ly, t.Color)
```
It's weird that the results are quite different.
![image](https://github.com/ebitenui/ebitenui/assets/6286655/6259b9f0-54f7-4af7-8013-7025c6f90d39)

So, with `lx=11` we still get ~6px offset from the left with a bitmap font.

**Comment by quasilyte** [comment]
Here is a code to play around this without ebitenui:

```go
package main

import (
	"fmt"
	"image/color"
	"log"

	"github.com/hajimehoshi/bitmapfont/v2"
	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/text"
	"github.com/hajimehoshi/ebiten/v2/vector"
)

type Game struct {
}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	ff := bitmapfont.Face
	white := color.RGBA{R: 255, G: 255, B: 255, A: 255}
	green := color.RGBA{G: 255, A: 255}
	offsets := []int{10, 30, 50, 70}
	dy := 20
	for _, dx := range offsets {
		text.Draw(screen, fmt.Sprintf("Hello, offset_x=%d", dx), ff, dx, dy, white)
		dy += 20
		vector.StrokeLine(screen, float32(dx), 0, float32(dx), float32(200), 1, green, true)
	}
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return 640, 480
}

func main() {
	ebiten.SetWindowSize(640, 480)
	ebiten.SetWindowTitle("bitmapfont")
	if err := ebiten.RunGame(&Game{}); err != nil {
		log.Fatal(err)
	}
}
```

![image](https://github.com/ebitenui/ebitenui/assets/6286655/fe57bdd1-d727-4894-934f-8721f3356b82)

**Comment by hajimehoshi** [comment]
This seems correct as the green line should indicate a dot position. What about using `.` instead of `H`?

**Comment by quasilyte** [comment]
The dot position looks good.
Although I'm so confused now. :sweat_smile: 
It looks like the line at x=70 has offset of ~85 pixels.
![image](https://github.com/ebitenui/ebitenui/assets/6286655/13c93eec-9866-441e-b8b5-ec134e49c2aa)
I tried using fixed-size layouts (just returning `640, 480`) as well as this:
```go
func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return outsideWidth, outsideHeight
}
```
Maybe some scaling is still going on there.

**Comment by hajimehoshi** [comment]
Hmm, interestingly, `font.BoundString` doesn't use an origin position as a dot position with other fonts like Noto Sans CJK JP. (e.g. with 32-size Noto Sans CJK JP, `b, _, _ := f.Glyph('.'); b.Min.X` was a positive value, which was close to 0. I epxected this a negative value as the center should be (0, 0).)

**Comment by quasilyte** [comment]
The `GlyphBounds` could be the culprit here too.
The default ebitenui example font (centered correctly) bounds: `{{0:00 -6:00} {6:00 0:00}}`
The bitmap font bounds: `{{-4:00 -12:00} {2:00 4:00}}`
Notice the `-4` x-axis offset.
If I add `4` to the `text.Draw()` x argument, the result looks more centered.

I think that either bitmapfont should adjust the `GlyphBounds`-returned data or `drawGlyph` inside Ebitengine should handle this information differently. If the current behavior is expected, then perhaps ebitenui should provide some cludges to make such fonts center-alignable (it can detect `Face.GlyphBounds` returning negative x offset or something).

P.S. - the vertical alignment seems to be off too.

**Comment by quasilyte** [comment]
I'm getting really weird results for multi-line texts too.
![image](https://github.com/ebitenui/ebitenui/assets/6286655/b69db9f4-8cdb-4cb7-b136-1c5fde97108b)
Notice how the Y offset of the last button label is different.
They're all supposed to be aligned to the center of the button rectangle (and they are aligned if a different font is used.
![image](https://github.com/ebitenui/ebitenui/assets/6286655/91e1967c-c141-408d-a18b-a7ba4ed93b05)

**Comment by mcarpenter622** [comment]
The more I look at this the more I think it has something to do with the dot positioning in the bitmap font lib. For all the TTF fonts I've tested it is aligned as expected. It seems like the bitmap font is expecting the draw X position to be the end of the rune while the TTFs are expecting the draw X position to be the start of the rune. I don't think this is a problem with ebitenui. As far as a workaround in the meantime you can adjust the TextPadding to be biased on the left side:

```
	widget.ButtonOpts.TextPadding(widget.Insets{
			Left:   34, // + 4
			Right:  26, // - 4
			Top:    5,
			Bottom: 5,
		}),
``` 

Take a look at this:
![image](https://github.com/ebitenui/ebitenui/assets/13891542/d4d46a20-da21-4e2a-baf1-add089914387)

```
package main

import (
	"fmt"
	"image/color"
	"log"

	"github.com/golang/freetype/truetype"
	"github.com/hajimehoshi/bitmapfont/v2"
	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/text"
	"github.com/hajimehoshi/ebiten/v2/vector"
	"golang.org/x/image/font"
	"golang.org/x/image/font/gofont/goregular"
)

type Game struct {
}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	bmf := bitmapfont.Face
	ff, _ := loadFont(11)
	white := color.RGBA{R: 255, G: 255, B: 255, A: 255}
	green := color.RGBA{G: 255, A: 255}
	offsets := []int{10, 30, 50, 70}
	dy := 20
	for _, dx := range offsets {
		text.Draw(screen, fmt.Sprintf("TTF Font, offset_x=%d", dx), ff, dx, dy, white)
		text.Draw(screen, fmt.Sprintf("BMF Font, offset_x=%d", dx), bmf, dx, dy+15, white)
		dy += 30
		vector.StrokeLine(screen, float32(dx), 0, float32(dx), float32(200), 1, green, true)
	}
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return 640, 480
}

func main() {
	ebiten.SetWindowSize(640, 480)
	ebiten.SetWindowTitle("bitmapfont")
	if err := ebiten.RunGame(&Game{}); err != nil {
		log.Fatal(err)
	}
}

func loadFont(size float64) (font.Face, error) {
	ttfFont, err := truetype.Parse(goregular.TTF)
	if err != nil {
		return nil, err
	}

	return truetype.NewFace(ttfFont, &truetype.Options{
		Size:    size,
		DPI:     72,
		Hinting: font.HintingFull,
	}), nil
}

```

**Comment by hajimehoshi** [comment]
OK so this seems an issue in the bitmap font:

https://pkg.go.dev/golang.org/x/image/font#Face
https://developer.apple.com/library/archive/documentation/TextFonts/Conceptual/CocoaTextArchitecture/Art/glyphterms_2x.png

I'll fix this by updating the major version.

**Comment by hajimehoshi** [comment]
I expected that the center of the dot is (0, 0) from the comment

```
	// GlyphBounds returns the bounding box of r's glyph, drawn at a dot equal
	// to the origin, and that glyph's advance width.
```

but actually this was not with some TTF/OTF fonts (the minimum X was a positive value). This is quite confusing.

**Comment by mcarpenter622** [comment]
Fonts are overly complicated. I barely understand how they work. I'm very impressed with your bitmap library but glad I don't have to work on it lol.

**Comment by hajimehoshi** [comment]
@quasilyte Please try github.com/hajimehoshi/bitmapfont/v3 (v3.0.0-alpha). Thanks,

**Comment by quasilyte** [comment]
I can confirm that v3 solves all of my problems.
It makes the examples above with and without ebitenui work as expected.
It also makes the in-game text aligned properly.

I also tried the [scaled bitmap version](https://gist.github.com/hajimehoshi/0c653819d925b4a458be014274081d4b) (Hajime would recognize this code, ahaha). It works correctly as well.

The multi-line text looks legit too.

@mcarpenter622 @hajimehoshi A big thanks for the fix and investigation. :)

@mcarpenter622 I'm using the bitmapfont because of its amazing multi-language support and great compatibility with pixel-art games. :) It's really neat. I think it will be useful in the upcoming Ebitengine game jam too!

**Comment by hajimehoshi** [comment]
I've created an issue about the comments: https://github.com/golang/go/issues/60501

**Comment by mcarpenter622** [comment]
Thanks @hajimehoshi and @quasilyte for working through this together! I'm going to go ahead and close this issue.
