### ISSUE TITLE
Text input cursor is not at the end when text is updated through the code

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#73]
If you create a text input widget and set its text value, selecting (focusing) the input would create a caret near the 1st character.
```go
textinput.InputText = "some data"
```
This behavior can be worked around with a new `DoGoEnd()` method, which could be a recommended way to solve this issue.
Let's think about it and come up with a recommended approach to handle it.

**Comment by mcarpenter622** [comment]
I dislike the idea of asking users to do that. I have gone ahead and made some changes to capture this and handle it gracefully. I've also exposed several of the methods in the TextInput widget to allow users to set up alternate controls if they wish. I'll upload this evening when I get off.

**Comment by mcarpenter622** [comment]
Check out the latest version https://github.com/ebitenui/ebitenui/releases/tag/v0.5.4
It should resolve this issue.
