### ISSUE TITLE
TabBook: disabling the 1st tab works unexpectedly

### ISSUE THREAD

**Issue by quasilyte** [mcarpenter622/ebitenui#74]
Steps to reproduce:

1. Open the demo example
2. Find the tabbook page code
3. Change i == 2 to i == 0 so the first tab gets disabled from the start
4. Open the tabbook demo page, you'll see the first tab contents and 0 tabs selected (none of them is highlighted)

Results:
![image](https://github.com/ebitenui/ebitenui/assets/6286655/989680d7-2ffb-4c60-a3fa-88122e4d8140)

Notable things:
* None of the tabs are selected (no yellow outline anywhere)
* The tab page shows the first tab contents
* The tab page contents are not disabled, even though `AutoDisableChildren` is used

Using `SetTab` doesn't change anything:

```go
c.AddChild(t)
t.SetTab(tabs[1])
```

Expected behavior: there should be a way to properly create a tabbok with the first tab being disabled from the start. It's a harder bet in terms of the corner-case behavior when all of the tabs are disabled, but I'm not sure it's the same issue. Right now I'm mostly concerned about setting the first selected tab. Clearly, a TabBook tries to select the 1st tab right away, but sometimes it's not the correct behavior. It should either select the first enabled tab, or let the user to specify it explicitly. Or maybe `SetTab` should work in this case since we already have this method.

**Comment by quasilyte** [comment]
Truth be told, `SetTab` doesn't work even without a disabled tab.
I'm not sure how to use it properly.

**Comment by mcarpenter622** [comment]
There are some issues with order of initialization with the radio group that is causing issues here. I'm working to resolve it now

**Comment by mcarpenter622** [comment]
This has been updated. I added an InitialTab configuration to define what tab should be the first selected. I also set it up so that if an InitialTab is not provided the system will default to the first non-disabled tab. 
Take a look at the latest commit (and soon release).
