### ISSUE TITLE
AnchorLayout only shows a single child.

### ISSUE THREAD

**Issue by nullism** [mcarpenter622/ebitenui#76]
There seems to be a bug positioning multiple elements on a screen with `AnchorLayout`. 

You can test by taking the `widget_demos/anchorlayout` and adding a second child container with a different anchor position. 

Here's an example:

```go
func main() {

	rootContainer := widget.NewContainer(
		widget.ContainerOpts.BackgroundImage(image.NewNineSliceColor(color.NRGBA{0, 0, 255, 255})),
		widget.ContainerOpts.Layout(widget.NewAnchorLayout(
			widget.AnchorLayoutOpts.Padding(widget.NewInsetsSimple(50)),
		)),
	)

	topLeftContainer := widget.NewContainer(
		widget.ContainerOpts.BackgroundImage(image.NewNineSliceColor(color.NRGBA{255, 0, 0, 255})),
		widget.ContainerOpts.WidgetOpts(
			widget.WidgetOpts.LayoutData(widget.AnchorLayoutData{
				HorizontalPosition: widget.AnchorLayoutPositionStart,
				VerticalPosition:   widget.AnchorLayoutPositionStart,
				StretchHorizontal:  false,
				StretchVertical:    false,
			}),
			widget.WidgetOpts.MinSize(100, 100),
		),
	)

	bottomRightContainer := widget.NewContainer(
		widget.ContainerOpts.BackgroundImage(image.NewNineSliceColor(color.NRGBA{0, 255, 0, 255})),
		widget.ContainerOpts.WidgetOpts(
			widget.WidgetOpts.LayoutData(widget.AnchorLayoutData{
				HorizontalPosition: widget.AnchorLayoutPositionEnd,
				VerticalPosition:   widget.AnchorLayoutPositionEnd,
				StretchHorizontal:  false,
				StretchVertical:    false,
			}),
			widget.WidgetOpts.MinSize(100, 100),
		),
	)

	rootContainer.AddChild(topLeftContainer)
	rootContainer.AddChild(bottomRightContainer) // never renders

	// construct the UI
	ui := ebitenui.UI{
		Container: rootContainer,
	}

	// Ebiten setup
	ebiten.SetWindowSize(800, 800)
	ebiten.SetWindowTitle("Ebiten UI - Multi-Container Layout")
	ebiten.SetWindowResizingMode(ebiten.WindowResizingModeEnabled)

	game := game{
		ui: &ui,
	}

	// run Ebiten main loop
	err := ebiten.RunGame(&game)
	if err != nil {
		log.Println(err)
	}
}

```

**What I expect** (I have not found a way to achieve this):
![image](https://github.com/ebitenui/ebitenui/assets/730290/c6801fd0-1edc-443c-bc6a-54ba4e0d22a3)

**What I get**:
![image](https://github.com/ebitenui/ebitenui/assets/730290/7f8beeb3-36b1-4574-8656-38099ed85656)

**Comment by mcarpenter622** [comment]
This actually working as expected. The anchor layout is built to only layout a single child. I believe the reasoning is "what do you do if two items are anchored to the same location.?". What you're trying to achieve can be done with a grid layout with 4 quarters instead, or a stacked layout.

**Comment by nullism** [comment]
> This actually working as expected

So an anchored layout is special in that it only allows a single child container? In this case, logging an error could be helpful.

> "what do you do if two items are anchored to the same location.?"

In that case, it seems like drawing one over the other makes sense. It makes _more sense_ than just silently hiding all subsequent containers (if that's what it's doing, appears to be the case). 

> What you're trying to achieve can be done with a grid layout with 4 quarters instead, or a stacked layout.

A grid layout was a no go as I expect to have variable sizes for the various anchored components of the screen (like a minimap, menu button, bottom hud, all varying widths and heights like you'd see in a typical game). 

Though I did give it a few hours trying to get this to work with a stacked layout. If you have an example of how I could handle this I'd greatly appreciate it!

One workaround has been to create multiple instances of `ebitenui.UI` and iterating them, but that feels like a hack.

**Comment by mcarpenter622** [comment]
The stacked layout example does pretty much what you're suggesting: https://ebitenui.github.io/stacked_layout/
-> https://github.com/ebitenui/ebitenui/blob/master/_examples/widget_demos/stackedlayout/main.go

So in regards to the grid layout, you can set it up in quadrants, so 2 columns 2 rows (or 3x3), each setup to stretch. Then add another containers to the individual corners so that you can add your various widgets where you want them. The grid layout just helps get the sub containers and widgets in the right places.

Another option to consider is to use a Window. Windows can be placed where ever you want with x/y coordinates. This is how I am handling the UI for my game. See  https://ebitenui.github.io/window/ -> https://github.com/ebitenui/ebitenui/blob/master/_examples/widget_demos/window/main.go

Along with that, Since I have added stacked layout that does allow overlapping widgets, I will leave this open as an enhancement to allow multiple children to be laid out in an anchor layout.

**Comment by nullism** [comment]
Awesome, thanks very much for the prompt replies! 

I'll see if I can figure out stacked layout with multiple anchored containers. 

Good ideas on the grid, but part of these elements may span the entirety of a grid row which makes that a bit tricky. 

Appreciate tagging this as an enhancement!

**Comment by mcarpenter622** [comment]
If you have any questions please join the discord and I'll be happy to help
ya out. I'm available most days after 5pm est. Gotta love those 8-5 jobs :)

So as far as the grid you could also make a single column grid with 3 rows.
A header body and footer essentially. Then add your widgets or additional
containers to the footer.

The key to these layouts is to use nesting containers.

**Comment by nullism** [comment]
Just in case anyone stumbles upon this, I was able to get this to work with your suggestion of using Windows with a `StackedLayout` for the root container. 

Since I couldn't position windows with Anchors, I just make a translation function (I'm sure there's a smarter way, but this seems to work) which I'm sharing here in case this will help others: 

```go

// getAnchorPosition returns the screen position of windows according to an anchor. 
// width and height are the results of `PreferredSize()` of the window's contents. 
// this also assumes ScreenWidth and ScreenHeight are accessible and exposed.
func getAnchorPosition(anchor AnchorPosition, width, height int) (int, int) {
	var x, y int

	centerX := (ScreenWidth / 2) - (width / 2)
	centerY := (ScreenHeight / 2) - (height / 2)
	rightX := ScreenWidth - width
	bottomY := ScreenHeight - height

	switch anchor {
	case TopLeft:
		x = 0
		y = 0
	case TopCenter:
		x = centerX
		y = centerY
	case TopRight:
		x = rightX
		y = 0
	case MiddleLeft:
		x = 0
		y = centerY
	case MiddleCenter:
		x = centerX
		y = centerY
	case MiddleRight:
		x = rightX
		y = centerY
	case BottomLeft:
		x = 0
		y = bottomY
	case BottomCenter:
		x = centerX
		y = bottomY
	case BottomRight:
		x = rightX
		y = bottomY
	}

	return x, y
}
```

**Comment by mcarpenter622** [comment]
This is complete now with the latest commit
