### ISSUE TITLE
Android: Focusing a Text Input does not open Android on screen keyboard

### ISSUE THREAD

**Issue by scratch85** [mcarpenter622/ebitenui#77]
Tried to use the demo on an Android phone, but the keyboard is not shown when focusing a Text Input.

**Comment by mcarpenter622** [comment]
Yea, that one is a bit annoying. I'm not actually sure how to resolve that one. I think it'll be a combination between the lib and some js in the html page hosting the app.

If you have any suggestions on how to resolve this I'd appreciate it!

**Comment by mcarpenter622** [comment]
Just a heads up. I've been playing with this one. I have a wip up https://ebitenui.github.io/textinput/

**Comment by scratch85** [comment]
Nice, worked for me. Many thanks.

Can you tell me what you have changed to make it work?

**Comment by mcarpenter622** [comment]
@scratch85 I wrote some code that opens a hidden text box via Javascript and then copies the inputs from that textbox into the ui lib. It's still a little "shaky" but seems to work.
https://github.com/ebitenui/ebitenui/blob/master/internal/jsUtil/util_js.go

**Comment by mcarpenter622** [comment]
I believe this is working now. I went ahead and cleaned up the change so you can now select the type of keyboard you want to open on  a mobile device! Please open a new issue if you find problems with this change =)  I'll be kicking out a new numbered release soonish but you can pull it by the latest commit. Thanks!
