### ISSUE TITLE
Text Area does not render text on mobile

### ISSUE THREAD

**Issue by nmorenor** [mcarpenter622/ebitenui#79]
I've started to use the latest changes for the input text which works great! The game I've been working on has a chat feature where you can send messages and it uses a text Area to render the messages, it works well on native and on desktop browser, but not on mobile browser, weird thing is that mobile browser can send messages (if other side is not mobile you do see the messages) but no text is rendered on mobile browser.

**Comment by mcarpenter622** [comment]
I am not sure this is still an issue. This demo works fine on the mobile browsers I've tested.
https://ebitenui.github.io/textarea/

I'll give it a few days and close it in I don't get a reply @nmorenor
