### ISSUE TITLE
Centering a button

### ISSUE THREAD

**Issue by mat007** [mcarpenter622/ebitenui#84]
Hi!

I’m trying to center a button vertically, and fail miserably.

For instance here is how I modified the demo, to wrap some buttons with an anchor layout:
```
diff --git a/_examples/demo/page.go b/_examples/demo/page.go
index bc91ffd..bfbb195 100644
--- a/_examples/demo/page.go
+++ b/_examples/demo/page.go
@@ -20,17 +20,22 @@ func buttonPage(res *uiResources) *page {

        bs := []*widget.Button{}
        for i := 0; i < 3; i++ {
+               bc := widget.NewContainer(widget.ContainerOpts.Layout(widget.NewAnchorLayout()))
                b := widget.NewButton(
-                       widget.ButtonOpts.WidgetOpts(widget.WidgetOpts.LayoutData(widget.RowLayoutData{
-                               Stretch: true,
-                       })),
+                       widget.ButtonOpts.WidgetOpts(
+                               widget.WidgetOpts.LayoutData(widget.AnchorLayoutData{
+                                       HorizontalPosition: widget.AnchorLayoutPositionCenter,
+                                       VerticalPosition:   widget.AnchorLayoutPositionCenter,
+                               }),
+                       ),
                        widget.ButtonOpts.Image(res.button.image),
                        widget.ButtonOpts.Text(fmt.Sprintf("Button %d", i+1), res.button.face, res.button.text),
                        widget.ButtonOpts.TextPadding(res.button.padding),
                        widget.ButtonOpts.CursorEnteredHandler(func(args *widget.ButtonHoverEventArgs) { fmt.Println("Cursor Entered: " + args.Button.Text().Label) }),
                        widget.ButtonOpts.CursorExitedHandler(func(args *widget.ButtonHoverEventArgs) { fmt.Println("Cursor Exited: " + args.Button.Text().Label) }),
                )
-               c.AddChild(b)
+               bc.AddChild(b)
+               c.AddChild(bc)
                bs = append(bs, b)
        }
```
Here is what I’m seeing:

![image](https://github.com/ebitenui/ebitenui/assets/2386884/b7de7955-8d41-4324-9d9f-ff44d3a2473e)

and here is what I was hoping for:

![image](https://github.com/ebitenui/ebitenui/assets/2386884/c6e68d80-f1b2-405f-820b-767d6ca0e64c)

Am I missing something?

When I look at the button implementation, it seems it’s actually made of a container with child elements (text and image): https://github.com/ebitenui/ebitenui/blob/7c662ee35a1eeecb05a220a1ea969728f9029e90/widget/button.go#L143-L156
Could this explain why the layout doesn’t get applied?

Thanks!

**Comment by mcarpenter622** [comment]
So from what I can tell its working as I'd expect. I'm pretty sure you
don't need that extra container and can use RowLayoutData to center them
instead since they are in a Row container.
The best way to see what is happening is give your containers a solid
background color to see where they are.

Also, check out the widget demos they are much easier to follow.

Good luck and let me know if that helps.

**Comment by mat007** [comment]
Oh thank you, it indeed helped me understand how to make it work.

Thanks, it’s a great library once past the initial learning of how to weave all the containers and widgets together. 😄
