### ISSUE TITLE
Cannot set button text position to TextPositionEnd

### ISSUE THREAD

**Issue by mat007** [mcarpenter622/ebitenui#88]
Hi!

Maybe I have missed something, but I’m struggling to create buttons which have their text aligned to the right side of the widget.

https://github.com/ebitenui/ebitenui/blob/378dd069aa75473ad0c9b1868f0bc4d9f528339c/widget/button.go#L164
creates a Text widget with
https://github.com/ebitenui/ebitenui/blob/378dd069aa75473ad0c9b1868f0bc4d9f528339c/widget/button.go#L178

Then
https://github.com/ebitenui/ebitenui/blob/378dd069aa75473ad0c9b1868f0bc4d9f528339c/widget/button.go#L140
is a copy-paste of `Text` with only `TextPositionStart` replacing the horizontal `TextPositionCenter`
https://github.com/ebitenui/ebitenui/blob/378dd069aa75473ad0c9b1868f0bc4d9f528339c/widget/button.go#L154

Maybe the latter function could be deprecated and there could be a `ButtonOpt` to configure the text position instead, e.g.
```
func (o ButtonOptions) TextPosition(h TextPosition, v TextPosition) ButtonOpt {
	return func(b *Button) {
		b.hTextPosition = h
		b.vTextPosition = v
	}
}
```
?

If that sounds sensible, I can create a pull request!

Thanks.

**Comment by mcarpenter622** [comment]
That's a really good suggestion. I'm not sure why the original developer
went in that direction but I'll see about fixing it. Thanks for pointing
that out!

Mark

**Comment by mat007** [comment]
I can create a pull request if you want!

**Comment by mcarpenter622** [comment]
Sure!, but my suggestion is to default to center center, then remove the
simple left method completely. At this point it is better to break things
to have a clean API. The library is still a wip and the fix is simple for
users.
